/**
 * Regenerate src/lib/blog/post-manifest.ts from content/blog/posts/*.json
 * Run: npm run sync:blog
 */
import fs from "node:fs";
import path from "node:path";
import { uniqueSlugVars } from "./lib/slugToVar.ts";

const postsDir = path.join(process.cwd(), "content/blog/posts");
const outFile = path.join(process.cwd(), "src/lib/blog/post-manifest.ts");

const files = fs
  .readdirSync(postsDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

const imports = uniqueSlugVars(files.map((file) => file.replace(/\.json$/, ""))).map(({ slug, varName }) => ({
  file: `${slug}.json`,
  varName,
  slug
}));

const importLines = imports
  .map(({ file, varName }) => `import ${varName} from "../../../content/blog/posts/${file}";`)
  .join("\n");

const arrayLines = imports.map(({ varName }) => `  ${varName},`).join("\n");

const content = `import type { BlogPost } from "@/types/blog";
${importLines}

/** Auto-generated by scripts/sync-blog-manifest.ts — do not edit by hand. */
export const postManifest: BlogPost[] = [
${arrayLines}
] as BlogPost[];
`;

fs.writeFileSync(outFile, content, "utf8");
console.log(`Updated post-manifest.ts with ${imports.length} posts.`);
