/**
 * Regenerate src/lib/blog/en-post-manifest.ts from content/blog/posts-en/*.json
 * Run: npm run sync:blog:en
 */
import fs from "node:fs";
import path from "node:path";
import { uniqueSlugVars } from "./lib/slugToVar.ts";

const postsDir = path.join(process.cwd(), "content/blog/posts-en");
const outFile = path.join(process.cwd(), "src/lib/blog/en-post-manifest.ts");

if (!fs.existsSync(postsDir)) {
  fs.mkdirSync(postsDir, { recursive: true });
}

const files = fs
  .readdirSync(postsDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

const imports = uniqueSlugVars(files.map((file) => file.replace(/\.json$/, ""))).map(({ slug, varName }) => ({
  file: `${slug}.json`,
  varName,
  slug
}));

const importLines = imports
  .map(({ file, varName }) => `import ${varName} from "../../../content/blog/posts-en/${file}";`)
  .join("\n");

const arrayLines = imports.map(({ varName }) => `  ${varName},`).join("\n");

const content = `import type { BlogPostTranslation } from "@/types/blog";
${importLines}

/** Auto-generated by scripts/sync-blog-en-manifest.ts — do not edit by hand. */
export const enTranslationManifest: BlogPostTranslation[] = [
${arrayLines}
] as BlogPostTranslation[];

export const enTranslationBySlug = new Map(enTranslationManifest.map((t) => [t.slug, t]));
`;

fs.writeFileSync(outFile, content, "utf8");
console.log(`Updated en-post-manifest.ts with ${imports.length} English translations.`);
