/**
 * Regenerate src/lib/blog/post-manifest.ts from content/blog/posts/*.json
 * Run: npm run sync:blog
 */
import fs from "node:fs";
import path from "node:path";

const postsDir = path.join(process.cwd(), "content/blog/posts");
const outFile = path.join(process.cwd(), "src/lib/blog/post-manifest.ts");

function slugToVar(slug: string) {
  return slug
    .split("-")
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("")
    .replace(/[^a-zA-Z0-9]/g, "");
}

const files = fs
  .readdirSync(postsDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

const imports = files.map((file) => {
  const slug = file.replace(/\.json$/, "");
  const varName = slugToVar(slug);
  return { file, varName, slug };
});

const importLines = imports
  .map(({ file, varName }) => `import ${varName} from "../../../content/blog/posts/${file}";`)
  .join("\n");

const arrayLines = imports.map(({ varName }) => `  ${varName},`).join("\n");

const content = `import type { BlogPost } from "@/types/blog";
${importLines}

/** Auto-generated by scripts/sync-blog-manifest.ts — do not edit by hand. */
export const postManifest: BlogPost[] = [
${arrayLines}
] as BlogPost[];
`;

fs.writeFileSync(outFile, content, "utf8");
console.log(`Updated post-manifest.ts with ${imports.length} posts.`);
